### ISSUE TITLE
Questions regarding the status / obstacles / potential of this project

### ISSUE THREAD

**Issue by MTDzi** [kloek/TorcsProject#6]
Hi,

I wanted to play a bit with behavioral cloning for self-driving cars, and was looking for a usable open-source platform -- that's how I stumbled upon TORCS. Next, I've looked for docker images for TORCS -- and that's how I got to your project.

Now, I'm not necessarily interested in using RL (not yet, at least), but the docker part of your project is exactly what I was looking for. But I did have a few questions, and I would very much appreciate if you found the time to answer them.

1. Have you encountered any impassable problems with TORCS? Meaning: was there any reason why you would now consider a different platform, and if so: which do you think is better? I've also considered the Udacity simulator: https://github.com/udacity/self-driving-car-sim but it 
2. Do you have a mind-map of what more can be done to improve this project? What should the next steps be?
3. I'm still looking into how to run the docker image but if you could perhaps point me in the right direction: I would like to be able to run TORCS and display it on my screen. Do you have a script for that?

Thank you for your time!

**Comment by kloek** [comment]
Hi,

I haven't worked with that project for over a year, and if i remember
correctly, it was a bit messy when i left it.

Torcs is a great little simulator for learning and playing around with RL,
and should then work with Behavioral Cloning (BC) as well, even though i
have no experience with BC,
but it is very limited, e.g. stepped mode only works without rendering
graphics.

When it comes to docker, i only tried it quickly, but abandoned it since i
had trouble getting it up on screen while running in docker, i know it
should be possible but i didn't want to waste time on it, so i just kept
running natively on my pc.

to your questions:
1. a. not being able to run in stepped mode with graphics sucks!
    b. lack of sensors limits the sim to very basic experiments/learning,
if you want to be able to scale up to more interesting stuff then a sim
that has lidar, and groundtruths for semantic segmentation makes it more
interesting! check out carla.org for example.
2. I have no intention of continuing on that project at the moment.
3. As, mentioned before, i never got the screen part to work ( didn't spend
much time on it) and i didn't have much exp with docker before that, so i
don't think i'm the right guy to help you there!

hope that atleast helps abit,

Regards,
Anton

**Comment by MTDzi** [comment]
Hey,

thanks a lot for your reply, I appreciate it :)

Carla looks VERY promising, especially [this](https://github.com/carla-simulator/imitation-learning) example of behavioral cloning and [this](https://github.com/carla-simulator/reinforcement-learning) example of RL. So yeah, I'm going to check that out.

Also, I've ran into this simulator by Microsoft RnD: https://github.com/Microsoft/AirSim (based on Unreal Engine 4, like Carla), and this simulator: https://github.com/CPFL/Autoware which is more integrated with ROS (?) but I have to admit I haven't found the time to really check it out.

For now, I think I'll try and join up with Carla, so thanks for that suggestion.

Again, thanks for your time!
